In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
dfTrue = pd.read_csv('True.csv')

In [4]:
#Adding new coloum in the data set which makes easy calculation 
dfTrue['NewsType'] = 1
dfTrue

,title,text,subject,date,NewsType
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [5]:
dfFake = pd.read_csv('Fake.csv')

In [6]:
#Adding new coloum in the data set which makes easy calculation 
dfFake['NewsType'] = 0

In [7]:
dfFake

,title,text,subject,date,NewsType
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
...,...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",0
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",0
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",0
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",0
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",0

In [8]:
# merging two data set  
data = pd.concat([dfTrue,dfFake])

In [9]:
data

,title,text,subject,date,NewsType
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1
...,...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",0
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",0
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",0
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",0
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",0

In [10]:
data

,title,text,subject,date,NewsType
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1
...,...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",0
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",0
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",0
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",0
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",0

In [11]:
data = data.sample(frac=1, random_state=42).reset_index(drop=True)

In [12]:
data

,title,text,subject,date,NewsType
0,BREAKING: GOP Chairman Grassley Has Had Enoug...,"Donald Trump s White House is in chaos, and th...",News,"July 21, 2017",0
1,Failed GOP Candidates Remembered In Hilarious...,Now that Donald Trump is the presumptive GOP n...,News,"May 7, 2016",0
2,Mike Pence’s New DC Neighbors Are HILARIOUSLY...,Mike Pence is a huge homophobe. He supports ex...,News,"December 3, 2016",0
3,California AG pledges to defend birth control ...,SAN FRANCISCO (Reuters) - California Attorney ...,politicsNews,"October 6, 2017",1
4,AZ RANCHERS Living On US-Mexico Border Destroy...,Twisted reasoning is all that comes from Pelos...,politics,"Apr 25, 2017",0
...,...,...,...,...,...
44893,Nigeria says U.S. agrees delayed $593 million ...,ABUJA (Reuters) - The United States has formal...,worldnews,"December 27, 2017",1
44894,Boiler Room #62 – Fatal Illusions,Tune in to the Alternate Current Radio Network...,Middle-east,"June 29, 2016",0
44895,ATHEISTS SUE GOVERNOR OF TEXAS Over Display on...,I m convinced the Freedom From Religion group...,Government News,"Feb 27, 2016",0
44896,Republican tax plan would deal financial hit t...,WASHINGTON (Reuters) - The Republican tax plan...,politicsNews,"November 2, 2017",1
44897,U.N. refugee commissioner says Australia must ...,SYDNEY (Reuters) - The U.N. High Commissioner ...,worldnews,"November 1, 2017",1

In [13]:
data['original_text'] = data['title'] + " " + data['text']

In [14]:
data = data[['original_text', 'NewsType']]

In [15]:
data

                                           original_text  NewsType
0       BREAKING: GOP Chairman Grassley Has Had Enoug...         0
1       Failed GOP Candidates Remembered In Hilarious...         0
2       Mike Pence’s New DC Neighbors Are HILARIOUSLY...         0
3      California AG pledges to defend birth control ...         1
4      AZ RANCHERS Living On US-Mexico Border Destroy...         0
...                                                  ...       ...
44893  Nigeria says U.S. agrees delayed $593 million ...         1
44894  Boiler Room #62 – Fatal Illusions Tune in to t...         0
44895  ATHEISTS SUE GOVERNOR OF TEXAS Over Display on...         0
44896  Republican tax plan would deal financial hit t...         1
44897  U.N. refugee commissioner says Australia must ...         1

[44898 rows x 2 columns]

In [16]:
##now text cleaning will start

In [17]:
import re
import string
from nltk.corpus import stopwords

In [18]:
def remove_tags(text):
    text = str(text)
    clean_text = re.sub(re.compile('<.*?>'),'',text)
    return clean_text

def remove_urls(text):
    text = str(text)
    pattern = re.compile(r'https?://\s+\www\.\s+')
    return pattern.sub(r'',text)

exclude = string.punctuation
def remove_punc(text):
    return text.translate(str.maketrans('','',exclude))
stop_words = set(stopwords.words('english'))
def remove_stopwords(text):
    new_text=[]
    for word in text.split():
        if word in stop_words:
            new_text.append('')
        else:
            new_text.append(word)


    x = new_text[:]
    new_text.clear()
    return ' '.join(x)

In [19]:
data['original_text']= data['original_text'].apply(remove_tags)
data['original_text'] = data['original_text'].apply(lambda x: x.lower())
data['original_text'] = data['original_text'].apply(remove_urls)
data['original_text'] = data['original_text'].apply(remove_punc)
data['original_text'] = data['original_text'].apply(remove_stopwords)

In [20]:
data

                                           original_text  NewsType
0      breaking gop chairman grassley   enough demand...         0
1      failed gop candidates remembered  hilarious mo...         0
2      mike pence’s new dc neighbors  hilariously tro...         0
3      california ag pledges  defend birth control in...         1
4      az ranchers living  usmexico border destroy na...         0
...                                                  ...       ...
44893  nigeria says us agrees delayed 593 million fig...         1
44894  boiler room 62 – fatal illusions tune    alter...         0
44895  atheists sue governor  texas  display  capitol...         0
44896  republican tax plan would deal financial hit  ...         1
44897  un refugee commissioner says australia must st...         1

[44898 rows x 2 columns]

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier

In [22]:
tfidf = TfidfVectorizer(max_features=5000) # max
X = tfidf.fit_transform(data['original_text'])
y = data['NewsType']

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
print("Text representation complete! Vectorized matrix shape:", X.shape)

Text representation complete! Vectorized matrix shape: (44898, 5000)

In [25]:
rf = RandomForestClassifier()

In [26]:
rf.fit(X_train,y_train)

RandomForestClassifier()

In [32]:
y_pred = rf.predict(X_test)

In [33]:
accuracy_score(y_test,y_pred)

0.9973273942093541

In [34]:
# Print the full classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4669
           1       1.00      1.00      1.00      4311

    accuracy                           1.00      8980
   macro avg       1.00      1.00      1.00      8980
weighted avg       1.00      1.00      1.00      8980

In [35]:
def predict_custom_news(custom_text):
    cleaned_text = remove_tags(custom_text)
    cleaned_text = cleaned_text.lower() 
    cleaned_text = remove_urls(cleaned_text)
    cleaned_text = remove_punc(cleaned_text)
    cleaned_text = remove_stopwords(cleaned_text)
    

    vectorized_text = tfidf.transform([cleaned_text])

    prediction = rf.predict(vectorized_text)
    probabilities = rf.predict_proba(vectorized_text)
    
    fake_prob = probabilities[0][0] * 100
    real_prob = probabilities[0][1] * 100
    
    print(f"Text: '{custom_text}'\n")
    print(f"📊 Probability Breakdowns:")
    print(f"🔴 Fake News Confidence: {fake_prob:.2f}%")
    print(f"🟢 Real News Confidence: {real_prob:.2f}%")
    print("-" * 40)
    if real_prob > fake_prob:
        print("Verdict: REAL NEWS")
    else:
        print("Verdict: FAKE NEWS")

In [40]:
my_news = " india wins the world cup "

In [41]:
predict_custom_news(my_news)

Text: ' india wins the world cup '

📊 Probability Breakdowns:
🔴 Fake News Confidence: 99.00%
🟢 Real News Confidence: 1.00%
----------------------------------------
Verdict: FAKE NEWS